### ISSUE TITLE
Настроить больше автоматических проверок кода на Travis

### ISSUE THREAD

**Issue by kirill-korniakov** [UNN-VMK-Software/agile-course-theory#38]
**TODO**
- [ ] Проверить что нет неправильных зависимостей между модулями
- [ ] Можно ли как-то запускать проверки, которые делает IDEA?
  - [ ] Ее предложения по упрощению кода.

**DONE**
- [x] Включить проверку стиля (CPD), но нужно выбрать стиль
- [x] Автоматический поиск дублирующегося кода (commit script to the repo)
  - [x] http://docs.codehaus.org/display/GRADLE/Cookbook#Cookbook-usingPMD
- [x] PMD умеет огромную кучу всего
  - [x] Ненужные `import`-команды
